apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: safatu/python-web
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
