site_name: 'python-app'
site_description: 'Main documentation for python-app features and framework APIs'
repo_url: https://github.com/sasfatu/python-web
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  - search
  - mermaid2

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Worum gehts?: 'docs/index.md'

theme:
  name: material
  palette:
    primary: teal

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.superfences
