replicaCount: 1
image:
  repository: gileo/python-app
  tag: a1ac2a
  pullPolicy: IfNotPresent
livenessProbe:
  httpGet:
    path: /api/v1/healthz
    port: 5050
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /api/v1/healthz
    port: 5050
  initialDelaySeconds: 5
  periodSeconds: 10
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 5050
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: python-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  requests:
    cpu: 50m
    memory: 50M
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
